language: java
sudo: false
script: mvn clean verify
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)


notifications:
  email:
    recipients:
      - kimrr@stud.ntnu.no
      - k-riro@online.no
    on_failure: always
    on_success: never